# Site settings

domain: machinetranslate.org
url: https://machinetranslate.org
title: Machine Translate
description: Open resources and community for machine translation

# Pages permalink
permalink: pretty
# TODO: remove this by moving them all under a content/ directory
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: /machinetranslate.png
      seo:
        type: Article
  -
    scope:
      path: "applications"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "approaches"
      type: "pages"
    values:
      permalink: /:basename
  -
      scope:
        path: "concepts"
        type: "pages"
      values:
        permalink: /:basename
  -
    scope:
      path: "industry"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "contributing"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: WebPage
  -
    scope:
      path: "community"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "customisation"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "events"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: Event
  -
    scope:
      path: "apis"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: Product
  -
    scope:
      path: "languages"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: Language
  -
    scope:
      path: "associations"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: Association
  -
    scope:
      path: "people"
      type: "pages"
    values:
      permalink: /:basename
      seo:
        type: Person
  -
    scope:
      path: "quality"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "research"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "workflows"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "building-and-research"
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: "products-and-applications"
      type: "pages"
    values:
      permalink: /:basename

# Just the Docs

remote_theme: pmarsceill/just-the-docs@v0.3.3

logo: favicon.ico
color_scheme: swissred

search:
  rel_url: false
  button: true
  heading_level: 3

last_edit_timestamp: true

back_to_top: true
back_to_top_text: â†‘

# Google Analytics
ga_tracking: G-MJD8MHH513

# Plugins

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-seo-tag
  - html-proofer

# Default theme settings
# Unused
minima:
  social_links:
    github: machinetranslate
    twitter: machtranslate
    facebook: machinetranslate
    linkedin: machinetranslate

# SEO settings

seo:
  type: organization

social:
  github: machinetranslate
  twitter: machtranslate
  facebook: machinetranslate
  linkedin: machinetranslate
