# Site settings

---
domain: machinetranslate.org
url: https://machinetranslate.org
title: Machine Translate
tagline: Open information and community for machine translation
description: Open information and community for machine translation, to make
  machine translation accessible to more people.

# Pages permalink
permalink: pretty

# TODO: remove this by moving them all under a content/ directory
defaults:
  - scope:
      path: ""
      type: pages
    values:
      image: /machinetranslate.png
      seo:
        type: Article
  - scope:
      path: applications
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: approaches
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: calls-for-papers
      type: pages
    values:
      permalink: /:basename
      seo:
        type: ItemList
  - scope:
      path: concepts
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: industry
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: contributing
      type: pages
    values:
      permalink: /:basename
      seo:
        type: WebPage
  - scope:
      path: community
      type: pages
    values:
      permalink: /:basename
      seo:
        type: WebPage
  - scope:
      path: customisation
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: events
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Event
  - scope:
      path: apis
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Product
  - scope:
      path: integrations
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Product
  - scope:
      path: languages
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Language
  - scope:
      path: associations
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Association
  - scope:
      path: people
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Person
  - scope:
      path: quality
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: research-laboratories
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: workflows
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: building-and-research
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: aggregators
      type: pages
    values:
      permalink: /:basename
      seo:
        type: ItemList
  - scope:
      path: features
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: resources
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: about
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: more
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: community
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article
  - scope:
      path: newsletter
      type: pages
    values:
      permalink: /:basename
      seo:
        type: Article

# Just the Docs
remote_theme: pmarsceill/just-the-docs@v0.5.4
logo: favicon.ico
color_scheme: swissred
search:
  rel_url: false
  button: true
  heading_level: 3
last_edit_timestamp: true
back_to_top: true
back_to_top_text: â†‘

# Google Analytics
ga_tracking: G-MJD8MHH513

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-seo-tag
  - html-proofer
  - jekyll-include-cache

# Default theme settings
# Unused
minima:
  social_links:
    github: machinetranslate
    twitter: machtranslate
    facebook: machinetranslate
    linkedin: machinetranslate

# SEO settings
seo:
  type: organization
twitter:
  username: machtranslate
  card: summary
facebook:
  publisher: https://www.facebook.com/machinetranslate
social:
  name: Machine Translate | machinetranslate.org
  links:
    - https://github.com/machinetranslate
    - https://twitter.com/machtranslate
    - https://www.linkedin.com/company/machinetranslate
    - https://www.facebook.com/machinetranslate

lsi: false

incremental: true

# Build settings
# Note that .files are excluded by default.
exclude:
  - .bundle
  - README.md
  - generate.py
  - .sass-cache/
  - .jekyll-cache/   
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
